module.exports = {
    "nick": "Jak vám říkají 🤠",
    "mail": "Emajl 💌",
    "link": "Jste taky 🙃 a máte 🌐? (http://)",
    "nickFail": "Něco delšjeho, prosím ✏️",
    "mailFail": "Potvrďte svůj emajl",
    "sofa": "Nikdo se zatím neodvážil vznést námitku ani komentář 😿",
    "submit": "Plácnout to sem 👉",
    "reply": "Odpovědět 🧐",
    "cancelReply": "Raději neodpovědět 🤐",
    "comments": "Kometářů 🗯️",
    "cancel": "Zrušit ❌",
    "confirm": "Potvrdit ✔️",
    "continue": "Pokračovat 🤜",
    "more": "Více... 🙄",
    "preview": "Jak to vypadá, když se to převede na fešný formát 🌼",
    "emoji": "Smajly",
    "expand": "Rozbalit 🧻",
    "seconds": "sekund zpátky",
    "minutes": "minut zpátky",
    "hours": "hodin zpátky",
    "days": "dní zpátky",
    "now": "⚡ fčil",
    "uploading": "Nahrávání...",
    "uploadDone": "Nahrávání dokončeno!",
    "busy": "Počkejte prosím, nějak se to zakuckalo 🤧...",
    "code-98": "Inicializace komentářů Valine chcípla, please check your version of av-min.js.",
    "code-99": "Inicializace komentářů Valine chcípla, Please check the `el` element in the init method.",
    "code-100": "Inicializace komentářů Valine chcípla, Please check your appId and appKey.",
    "code-140": "Celkový počet lidí, kteří po mě dneska něco chtěli už překročil můj denní limit, takže zkuste zítra, no 😓",
    "code-401": "Achtung! Tuhle operaci byste nemšli mít právo udělat 📣, please check your appId and appKey.",
    "code-403": "Access denied by API domain white list, Please check your security domain."
};